import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed': '#002202',
        'on-primary': '#003a05',
        'on-tertiary-container': '#68c1e7',
        'tertiary-fixed-dim': '#79d1f8',
        'secondary-container': '#374951',
        'secondary-fixed': '#d2e6ef',
        'on-tertiary': '#003546',
        'surface-container': '#1e2020',
        'outline': '#8b9386',
        'on-surface-variant': '#c1c9bb',
        'primary-fixed': '#b3f3a6',
        'on-tertiary-fixed': '#001f2a',
        'surface-tint': '#98d68c',
        'primary-container': '#1a5319',
        'surface-dim': '#121414',
        'outline-variant': '#41493e',
        'on-primary-fixed-variant': '#185218',
        'on-background': '#e2e2e2',
        'on-error': '#690005',
        'surface-container-highest': '#333535',
        'inverse-primary': '#326a2d',
        'surface-variant': '#333535',
        'on-secondary': '#21333a',
        'on-secondary-container': '#a5b8c1',
        'surface-container-lowest': '#0d0f0f',
        'on-error-container': '#ffdad6',
        'error-container': '#93000a',
        'tertiary-fixed': '#bee9ff',
        'tertiary-container': '#004e66',
        'on-tertiary-fixed-variant': '#004d64',
        'background': '#121414',
        'surface-container-high': '#282a2a',
        'surface-container-low': '#1a1c1c',
        'on-secondary-fixed': '#0b1e24',
        'secondary': '#b6cad2',
        'primary-fixed-dim': '#98d68c',
        'on-surface': '#e2e2e2',
        'tertiary': '#79d1f8',
        'inverse-on-surface': '#2f3131',
        'inverse-surface': '#e2e2e2',
        'surface-bright': '#383939',
        'secondary-fixed-dim': '#b6cad2',
        'surface': '#121414',
        'error': '#ffb4ab',
        'primary': '#98d68c',
        'on-secondary-fixed-variant': '#374951',
        'on-primary-container': '#89c67e',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'fade-in': {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        shimmer: 'shimmer 2s infinite linear',
        'fade-in': 'fade-in 0.3s ease-out',
      },
    },
  },
  plugins: [],
};

export default config;
